using System;
namespace Dynamo.Nodes
{
	public static partial class BuiltinNodeCategories
	{
		public const string AUTODESK_REVIT_DB_MESH = "Autodesk.Revit.DB.Mesh";
		public const string AUTODESK_REVIT_DB_ELLIPSE = "Autodesk.Revit.DB.Ellipse";
		public const string AUTODESK_REVIT_CREATION_ITEMFACTORYBASE = "Autodesk.Revit.Creation.ItemFactoryBase";
		public const string AUTODESK_REVIT_DB_ADAPTIVECOMPONENTFAMILYUTILS = "Autodesk.Revit.DB.AdaptiveComponentFamilyUtils";
		public const string AUTODESK_REVIT_DB_CYLINDRICALFACE = "Autodesk.Revit.DB.CylindricalFace";
		public const string AUTODESK_REVIT_DB_CONICALFACE = "Autodesk.Revit.DB.ConicalFace";
		public const string AUTODESK_REVIT_DB_RULEDFACE = "Autodesk.Revit.DB.RuledFace";
		public const string AUTODESK_REVIT_DB_HERMITESPLINE = "Autodesk.Revit.DB.HermiteSpline";
		public const string AUTODESK_REVIT_DB_BLEND = "Autodesk.Revit.DB.Blend";
		public const string AUTODESK_REVIT_DB_SWEEP = "Autodesk.Revit.DB.Sweep";
		public const string AUTODESK_REVIT_DB_ADAPTIVECOMPONENTINSTANCEUTILS = "Autodesk.Revit.DB.AdaptiveComponentInstanceUtils";
		public const string AUTODESK_REVIT_DB_MODELARC = "Autodesk.Revit.DB.ModelArc";
		public const string AUTODESK_REVIT_DB_FORM = "Autodesk.Revit.DB.Form";
		public const string AUTODESK_REVIT_DB_BOUNDINGBOXUV = "Autodesk.Revit.DB.BoundingBoxUV";
		public const string AUTODESK_REVIT_DB_TRANSFORM = "Autodesk.Revit.DB.Transform";
		public const string AUTODESK_REVIT_DB_FACE = "Autodesk.Revit.DB.Face";
		public const string AUTODESK_REVIT_DB_FAMILYINSTANCE = "Autodesk.Revit.DB.FamilyInstance";
		public const string AUTODESK_REVIT_DB_DIVIDEDSURFACE = "Autodesk.Revit.DB.DividedSurface";
		public const string AUTODESK_REVIT_DB_POINTCLOUDINSTANCE = "Autodesk.Revit.DB.PointCloudInstance";
		public const string AUTODESK_REVIT_DB_GEOMETRYINSTANCE = "Autodesk.Revit.DB.GeometryInstance";
		public const string AUTODESK_REVIT_CREATION_APPLICATION = "Autodesk.Revit.Creation.Application";
		public const string AUTODESK_REVIT_DB_REVOLUTION = "Autodesk.Revit.DB.Revolution";
		public const string AUTODESK_REVIT_DB_LEVEL = "Autodesk.Revit.DB.Level";
		public const string AUTODESK_REVIT_DB_LINE = "Autodesk.Revit.DB.Line";
		public const string AUTODESK_REVIT_DB_MATERIAL = "Autodesk.Revit.DB.Material";
		public const string AUTODESK_REVIT_DB_SWEPTBLEND = "Autodesk.Revit.DB.SweptBlend";
		public const string AUTODESK_REVIT_DB_WALL = "Autodesk.Revit.DB.Wall";
		public const string AUTODESK_REVIT_DB_ELEMENTTRANSFORMUTILS = "Autodesk.Revit.DB.ElementTransformUtils";
		public const string AUTODESK_REVIT_DB_REFERENCEPOINT = "Autodesk.Revit.DB.ReferencePoint";
		public const string AUTODESK_REVIT_DB_MODELHERMITESPLINE = "Autodesk.Revit.DB.ModelHermiteSpline";
		public const string AUTODESK_REVIT_DB_INSTANCE = "Autodesk.Revit.DB.Instance";
		public const string AUTODESK_REVIT_CREATION_FAMILYITEMFACTORY = "Autodesk.Revit.Creation.FamilyItemFactory";
		public const string AUTODESK_REVIT_DB_MODELELLIPSE = "Autodesk.Revit.DB.ModelEllipse";
		public const string AUTODESK_REVIT_DB_POLYLINE = "Autodesk.Revit.DB.PolyLine";
		public const string AUTODESK_REVIT_DB_HERMITEFACE = "Autodesk.Revit.DB.HermiteFace";
		public const string AUTODESK_REVIT_CREATION_DOCUMENT = "Autodesk.Revit.Creation.Document";
		public const string AUTODESK_REVIT_DB_CURVE = "Autodesk.Revit.DB.Curve";
		public const string AUTODESK_REVIT_DB_XYZ = "Autodesk.Revit.DB.XYZ";
		public const string AUTODESK_REVIT_DB_POINT = "Autodesk.Revit.DB.Point";
		public const string AUTODESK_REVIT_DB_ARC = "Autodesk.Revit.DB.Arc";
		public const string AUTODESK_REVIT_DB_BOUNDINGBOXXYZ = "Autodesk.Revit.DB.BoundingBoxXYZ";
		public const string AUTODESK_REVIT_DB_COLOR = "Autodesk.Revit.DB.Color";
		public const string AUTODESK_REVIT_DB_GENERICFORM = "Autodesk.Revit.DB.GenericForm";
		public const string AUTODESK_REVIT_DB_EXTRUSION = "Autodesk.Revit.DB.Extrusion";
		public const string AUTODESK_REVIT_DB_REVOLVEDFACE = "Autodesk.Revit.DB.RevolvedFace";
		public const string AUTODESK_REVIT_DB_EDGE = "Autodesk.Revit.DB.Edge";
		public const string AUTODESK_REVIT_DB_MODELLINE = "Autodesk.Revit.DB.ModelLine";
		public const string AUTODESK_REVIT_DB_UV = "Autodesk.Revit.DB.UV";
		public const string AUTODESK_REVIT_DB_MODELSPLINE = "Autodesk.Revit.DB.ModelSpline";
		public const string AUTODESK_REVIT_DB_SOLID = "Autodesk.Revit.DB.Solid";
		public const string AUTODESK_REVIT_DB_PROFILE = "Autodesk.Revit.DB.Profile";
		public const string AUTODESK_REVIT_DB_MODELCURVE = "Autodesk.Revit.DB.ModelCurve";
		public const string AUTODESK_REVIT_DB_NURBSPLINE = "Autodesk.Revit.DB.NurbSpline";
		public const string AUTODESK_REVIT_DB_ADAPTIVEPOINTTYPE = "Autodesk.Revit.DB.AdaptivePointType";
	}
}
